spring.application.name=api
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.example.api=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO

# Common database properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false