# Production environment database configuration
spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USERNAME}
spring.datasource.password=${PROD_DB_PASSWORD}

# Ensure JPA doesn't modify schema in production
spring.jpa.hibernate.ddl-auto=validate

# Disable Flyway for production
spring.flyway.enabled=false